### ISSUE TITLE
`dpkg` upgrades don't work out-of-the-box

### ISSUE THREAD

**Issue by pwnfoo** [cheqd/cheqd-node#159]
## What?

Hi, I upgraded my node to the latest testnet and noticed that the dpkg upgrade process does not upgrade the testnet out-of-the-box.

Upon some digging, I figured that  `/var/lib/cheqd/data/` (remains from the previous `cosmosxx` address testnet) was still lying around. Due to this, the new `cheqd-noded` binary would not start, eventually failing to run the node.

## Info

The easiest way to tackle this would be to run `cheqd-noded unsafe-reset-all` after the upgrade process. maybe adding it to the [postinst script](https://github.com/cheqd/cheqd-node/blob/main/build_tools/postinst). From the help page : 
<pre>
unsafe-reset-all  resets the blockchain database, removes address book files, and 
                  resets data/priv_validator_state.json to the genesis state
</pre>

This command plays safe with the private keys as well (unlike the name), and does not reset the private keys.

**Comment by ankurdotb** [comment]
This specific issue was relevant because the binary and config folders changed between the versions in scope here. Since this is now stable and fixed, this fix is superseded/not needed.
