### ISSUE TITLE
I can't find the main network node or the block browser

### ISSUE THREAD

**Issue by COLUD4** [cheqd/cheqd-node#229]
### Summary

I can't find the main network node or the block browser

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ankurdotb** [comment]
Hey @COLUD4 could you please let me know what you mean by "main network node"? Our network does have nodes online.

**Comment by COLUD4** [comment]
I can't find the public node of Cheqd, the execution of the node I built stops at this point. Here is the data for viewing status.



{
 
&nbsp; "jsonrpc": "2.0",
 
&nbsp; "id": 1,
 
&nbsp; "result": {
 
&nbsp; &nbsp; "node_info": {
 
&nbsp; &nbsp; &nbsp; "protocol_version": {
 
&nbsp; &nbsp; &nbsp; &nbsp; "p2p": "8",
 
&nbsp; &nbsp; &nbsp; &nbsp; "block": "11",
 
&nbsp; &nbsp; &nbsp; &nbsp; "app": "0"
 
&nbsp; &nbsp; &nbsp; },
 
&nbsp; &nbsp; &nbsp; "id": "96816f8bd8ea278ccaf6dc3694bcc1f8b77713b2",
 
&nbsp; &nbsp; &nbsp; "listen_addr": "tcp://0.0.0.0:26656",
 
&nbsp; &nbsp; &nbsp; "network": "cheqd-mainnet-1",
 
&nbsp; &nbsp; &nbsp; "version": "0.34.14",
 
&nbsp; &nbsp; &nbsp; "channels": "40202122233038606100",
 
&nbsp; &nbsp; &nbsp; "moniker": "MainNode15",
 
&nbsp; &nbsp; &nbsp; "other": {
 
&nbsp; &nbsp; &nbsp; &nbsp; "tx_index": "on",
 
&nbsp; &nbsp; &nbsp; &nbsp; "rpc_address": "tcp://127.0.0.1:26657"
 
&nbsp; &nbsp; &nbsp; }
 
&nbsp; &nbsp; },
 
&nbsp; &nbsp; "sync_info": {
 
&nbsp; &nbsp; &nbsp; "latest_block_hash": "46845A0ED9EAB8DF0B233C31B53A6136A1A2F7DBEC2BFF94D70B66CF39EC6CBD",
 
&nbsp; &nbsp; &nbsp; "latest_app_hash": "3306FDD4D2623342F98AF63AFF2AC87AFD89B9DF389D49BC38B1D7FD0FDAB1B7",
 
&nbsp; &nbsp; &nbsp; "latest_block_height": "13125",
 
&nbsp; &nbsp; &nbsp; "latest_block_time": "2021-11-17T14:03:57.382939451Z",
 
&nbsp; &nbsp; &nbsp; "earliest_block_hash": "0807591DC707E402465A6F4E7767FD8166279D6363D91A231F75F5B6DF2086C3",
 
&nbsp; &nbsp; &nbsp; "earliest_app_hash": "E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855",
 
&nbsp; &nbsp; &nbsp; "earliest_block_height": "1",
 
&nbsp; &nbsp; &nbsp; "earliest_block_time": "2021-11-11T14:47:05.733203Z",
 
&nbsp; &nbsp; &nbsp; "catching_up": true
 
&nbsp; &nbsp; },
 
&nbsp; &nbsp; "validator_info": {
 
&nbsp; &nbsp; &nbsp; "address": "8000BB519697392A90DB62055E229BC8A1A351B7",
 
&nbsp; &nbsp; &nbsp; "pub_key": {
 
&nbsp; &nbsp; &nbsp; &nbsp; "type": "tendermint/PubKeyEd25519",
 
&nbsp; &nbsp; &nbsp; &nbsp; "value": "FUKx9d9FYkgiqezoL7/gvY6ecMbM8JQ4ib57VSlW3Cg="
 
&nbsp; &nbsp; &nbsp; },
 
&nbsp; &nbsp; &nbsp; "voting_power": "0"
 
&nbsp; &nbsp; }
 
&nbsp; }
 
}


发自我的iPhone


------------------ Original ------------------
From: Ankur Banerjee ***@***.***&gt;
Date: Fri,Nov 19,2021 10:56 PM
To: cheqd/cheqd-node ***@***.***&gt;
Cc: bigcloud ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [cheqd/cheqd-node] I can't find the main network node or theblock browser (Issue #229)





 
Hey @COLUD4 could you please let me know what you mean by "main network node"? Our network does have nodes online.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by COLUD4** [comment]
> Hey @COLUD4 could you please let me know what you mean by "main network node"? Our network does have nodes online.

Can you provide public nodes?

**Comment by COLUD4** [comment]
0:07AM ERR error while stopping peer error="already stopped" module=p2p

**Comment by COLUD4** [comment]
问题已经解决了， 原因是max_packet_msg_payload_size=1024。 它太小了

**Comment by ankurdotb** [comment]
Our public RPC endpoint is https://rpc.cheqd.net, however you shouldn't need this during the build/install process.

**Comment by ankurdotb** [comment]
I'll close this issue for now as I hope the RPC endpoint above gives you the node details/API you need, but please do let me know in case it needs to be re-opened.
