### ISSUE TITLE
[Bug]: No such interface “org.freedesktop.DBus.Properties”

### ISSUE THREAD

**Issue by vudex** [cheqd/cheqd-node#241]
### Contact Details

vudex@yandex.ru

### What happened?

I'm hitting following problem when creating trying to create keys for validator node

```
cheqd@cheqd:~$  cheqd-noded keys add cheqemkeys
Error: No such interface “org.freedesktop.DBus.Properties” on object at path /
```

I'm using 

```
cheqd@cheqd:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
```

### Reproduction steps

```bash
1. Set up a node using following instructions https://docs.cheqd.io/node/docs/setup-and-configure/debian/deb-package-install

2. Execute command "cheqd-noded keys add cheqemkeys"
```

### Bug prevalence

everytine command is executed

### Environment

mainnet

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ankurdotb** [comment]
Hi @vudex, this is an issue with using keyring when using GUIs. Please try on a system with just CLI only.
