### ISSUE TITLE
[feature]:  Static validation check for uniqueness of the did fragment id.

### ISSUE THREAD

**Issue by anikitinDSR** [cheqd/cheqd-node#314]
### Contact Details

andrew.nikitin@cheqd.io

### What is the feature you'd like to see?

Did-Doc consists of segments, called fragments, like `verificationMethod` or others and each of them includes `id` field.
The main goal for this feature is to add a check that all of this ids are unique through the whole Did-Doc.
Example of Did-Doc:
```
{
  "@context": [
    "https://www.w3.org/ns/did/v1",
    "https://w3id.org/security/suites/jws-2020/v1",
    "https://w3id.org/security/suites/ed25519-2020/v1"
  ]
  "id": "did:example:123456789abcdefghi",
  
  "verificationMethod": [{
    "id": "did:example:123#_Qq0UL2Fq651Q0Fjd6TvnYE-faHiOpRlPVQcY_-tA4A",
    ....
    }
  }, {
    "id": "did:example:123456789abcdefghi#keys-2",
    ....
  }],
  "authentication": [{
    "id": "did:example:123456789abcdefghi#keys-3",
    ....
    }]
  
}
```
Here are 2 verification methods with ids `"did:example:123#_Qq0UL2Fq651Q0Fjd6TvnYE-faHiOpRlPVQcY_-tA4A"` and `"did:example:123456789abcdefghi#keys-2"` and `authentication` with id `"did:example:123456789abcdefghi#keys-3"`. 

### Link for context

https://w3c.github.io/did-core/ 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Toktar** [comment]
Specification: https://w3c.github.io/did-core/
