### ISSUE TITLE
[feature]: implement a schema module

### ISSUE THREAD

**Issue by anikitinDSR** [cheqd/cheqd-node#316]
### Contact Details

andrew.nikitin@cheqd.io

### What is the feature you'd like to see?

Here we want to implement Schema module on the ledger side.
There is an ADR which is not finished yet, but it can be used as a first step.
https://github.com/cheqd/cheqd-node/blob/main/architecture/adr-list/adr-008-identity-resources.md

### Link for context

https://w3c.github.io/did-core/ 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Toktar** [comment]
https://github.com/cheqd/cheqd-node/pull/330
