### ISSUE TITLE
[Bug]: Cannot add a key when using `keyring-backend=os`

### ISSUE THREAD

**Issue by andynog** [cheqd/cheqd-node#351]
### What went wrong?

Trying to add a key using `cheqd-noded` cli on a Linux machine doesn't work if `keyring-backend=os`, if using `keyring-backend=test` then it works.

### How can we reproduce this bug?

Testing on an `Ubuntu (20.04)` Linux machine. Using `cheqd-noded` version `0.6.0`.

Trying to add a key on my machine and setting the `keyring-backend` to `os` the key is not stored. But if I use `test` the key is stored.

Command to add key with `keyring-backend=os`
```
$ cheqd-noded keys add local-cheqd --keyring-backend=os

- name: local-cheqd-an
  type: local
  address: cheqd1rz9w6y0m2arqh...
  pubkey: '{"@type":"/cosmos.crypto.secp256k1.PubKey","key":"A/3AjLA..."}'
  mnemonic: ""

**Important** write this mnemonic phrase in a safe place.
It is the only way to recover your account if you ever forget your password.

twenty radar ...

```

I get prompt ("Choose a password for the new keyring") by the operating systems to set a password to store the key and I chose a password and confirm it. But if I query the keys it doesn't show up:

```
$ cheqd-noded keys list --keyring-backend=os
[]
```

Command to add key with `keyring-backend=test`
```
$ cheqd-noded keys add local-cheqd --keyring-backend=test

- name: local-cheqd
  type: local
  address: cheqd1q9c....
  pubkey: '{"@type":"/cosmos.crypto.secp256k1.PubKey","key":"A9+P8LqPR8cB...."}'
  mnemonic: ""


**Important** write this mnemonic phrase in a safe place.
It is the only way to recover your account if you ever forget your password.

poet glory...

```

And listing the keys in the `test` works:

```
$ cheqd-noded keys list --keyring-backend=test
- name: local-cheqd
  type: local
  address: cheqd1q9c...
  pubkey: '{"@type":"/cosmos.crypto.secp256k1.PubKey","key":"A9+P8LqPR8cB...."}'
  mnemonic: ""
```

### Environment

Not applicable

### Bug prevalence

Everytime I run the command

### Which browser/client application did you encounter the bug in? (if applicable)

Other

### Relevant log output

```shell
no logs, I've added the commands and messages above
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ankurdotb** [comment]
That's odd. What happens if you don't explicitly mention the keyring backend? (Our default is "os".)

We've done transactions using the binary, so I'm wondering what the issue could be here. Whether it's just the flag failing, or can't interact with "os" keyring at all.

**Comment by ankurdotb** [comment]
Also follow-up question: is this an Ubuntu server with a GUI/window environment installed?

**Comment by andynog** [comment]
Yes Ubuntu desktop (with a GUI)

**Comment by ankurdotb** [comment]
@andynog Thanks for clarifying that. So I understand that when using GUI environments, the `os` backend can fail because there might be multiple targets for it to use, e.g., both `seahorse` as well as `kwallet` might exist on the same system. Are you actually running this as a node/server/validator or just for local development purposes?

Your point on this working with `gaiad` is interesting. Will look into why that's the case...

**Comment by ankurdotb** [comment]
Closing this as likely an OS issue
