### ISSUE TITLE
[Bug]: Interactive installer fails if there are white-spaces in the Moniker

### ISSUE THREAD

**Issue by bjaanes** [cheqd/cheqd-node#352]
### What went wrong?

When setting up a new node, if the moniker name has any spaces in it, the process will fail at the `init` command:

```
*********  Executing command: sudo su -c 'cheqd-noded init Empower Validator' cheqd
Error: accepts 1 arg(s), received 2
```

I was also not able to restart the interactive installer afterward and just ended up recreating the whole server. So it was a bit annoying :)

Suggested fix: when provided moniker has white space in it just replace the variable with one that has quotes.

Workaround: Provide the moniker with quotes.

### How can we reproduce this bug?

1. Run the interactive installer as a new node
2. Provide a moniker, when asked, that has a white space in it
3. Provide the rest of the installer prompts
4. See the error shortly after the installers starts its work
...

### Environment

Not applicable

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ankurdotb** [comment]
This is fixed under #354. Thanks for flagging this up, it's a use case we should've caught!
